lib/modern_art_web/router.ex
defmodule ModernArtWeb.Router do
  use ModernArtWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {ModernArtWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ModernArtWeb do
    pipe_through :browser

    get "/", GameController, :new
    post "/new", GameController, :create
    live "/:name", PageLive, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", ModernArtWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: ModernArtWeb.Telemetry
    end
  end
end

lib/modern_art/application.ex
defmodule ModernArt.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    children = [
      # Start the Ecto repository
      ModernArt.Repo,
      # Start the Telemetry supervisor
      ModernArtWeb.Telemetry,
      # Start the PubSub system
      {Phoenix.PubSub, name: ModernArt.PubSub},
      # Start the Endpoint (http/https)
      ModernArtWeb.Endpoint
      # Start a worker by calling: ModernArt.Worker.start_link(arg)
      # {ModernArt.Worker, arg}
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: ModernArt.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    ModernArtWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/modern_art/games.ex
defmodule ModernArt.Games do
  @moduledoc """
  The Games context.
  """

  import Ecto.Query, warn: false
  alias ModernArt.Repo

  alias ModernArt.Games.Game

  @doc """
  Returns the list of games.

  ## Examples

      iex> list_games()
      [%Game{}, ...]

  """
  def list_games do
    Repo.all(Game)
  end

  @doc """
  Gets a single game.

  Raises `Ecto.NoResultsError` if the Game does not exist.

  ## Examples

      iex> get_game!(123)
      %Game{}

      iex> get_game!(456)
      ** (Ecto.NoResultsError)

  """
  def get_game!(id), do: Repo.get!(Game, id)

  def by_name!(name) do
    Repo.get_by(Game, name: name) # -> [ {:name, name } ]
  end

  @doc """
  Creates a game.

  ## Examples

      iex> create_game(%{field: value})
      {:ok, %Game{}}

      iex> create_game(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_game() do
    %Game{}
    |> Game.changeset(%{name: generate_name()})
    |> Repo.insert()
  end

  @doc """
  Generates a random name for a game.

  TODO add more entropy, make names more fun?
  3% chance of collision at 1000 items
  """
  def generate_name() do
    Enum.random(0..0xffffff) |> Integer.to_string(16)
  end

  @doc """
  Updates a game.

  ## Examples

      iex> update_game(game, %{field: new_value})
      {:ok, %Game{}}

      iex> update_game(game, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_game(%Game{} = game, attrs) do
    game
    |> Game.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a game.

  ## Examples

      iex> delete_game(game)
      {:ok, %Game{}}

      iex> delete_game(game)
      {:error, %Ecto.Changeset{}}

  """
  def delete_game(%Game{} = game) do
    Repo.delete(game)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking game changes.

  ## Examples

      iex> change_game(game)
      %Ecto.Changeset{data: %Game{}}

  """
  def change_game(%Game{} = game, attrs \\ %{}) do
    Game.changeset(game, attrs)
  end
end

lib/modern_art/games/game.ex
defmodule ModernArt.Games.Game do
  use Ecto.Schema
  import Ecto.Changeset

  schema "games" do
    field :name, :string

    timestamps()
  end

  @doc false
  def changeset(game, attrs) do
    game
    |> cast(attrs, [:name])
    |> validate_required([:name])
  end
end

lib/modern_art/repo.ex
defmodule ModernArt.Repo do
  use Ecto.Repo,
    otp_app: :modern_art,
    adapter: Ecto.Adapters.Postgres
end

lib/modern_art_web/controllers/game_controller.ex
defmodule ModernArtWeb.GameController do
  use ModernArtWeb, :controller

  alias ModernArt.Games
  alias ModernArt.Games.Game

  def new(conn, _params) do
    changeset = Games.change_game(%Game{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, _params) do
    case Games.create_game() do
      {:ok, game} ->
        conn
        |> put_flash(:info, "Game created successfully.")
        |> redirect(to: Routes.page_path(conn, :index, game.name))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"name" => name}) do
    game = Games.by_name!(name)
    render(conn, "show.html", game: game)
  end
end

lib/modern_art_web/live/page_live.ex
defmodule ModernArtWeb.PageLive do
  require Logger
  use ModernArtWeb, :live_view
  alias ModernArt.Games
  alias Phoenix.PubSub

  @topic inspect(__MODULE__)

  @impl true
  def mount(%{"name" => name}, _session, socket) do
    PubSub.subscribe(ModernArt.PubSub, topic(name))
    game = Games.by_name!(name)
    {:ok, assign(socket,
      game: game,
      msgs: [],
    )}
  end

  defp broadcast(socket, event) do
    PubSub.broadcast(
      ModernArt.PubSub,
      topic(socket.assigns.game.name),
      event
    )
    socket
  end

  defp noreply(socket) do
    {:noreply, socket}
  end

  def handle_event("send-message", %{"message" => msg}, socket) do
    socket
    |> broadcast({:new_msg, msg})
    |> noreply
  end

  def handle_info({:new_msg, msg}, socket) do
    socket
    |> assign(msgs: socket.assigns.msgs ++ [msg])
    |> noreply
  end
  
  defp topic(), do: @topic
  defp topic(game_name), do: topic() <> to_string(game_name)
end

lib/modern_art_web/views/error_view.ex
defmodule ModernArtWeb.ErrorView do
  use ModernArtWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/modern_art_web/views/game_view.ex
defmodule ModernArtWeb.GameView do
  use ModernArtWeb, :view
end

lib/modern_art_web/views/layout_view.ex
defmodule ModernArtWeb.LayoutView do
  use ModernArtWeb, :view
end

lib/modern_art_web/live/page_live.html.leex
<section class="phx-hero" style="background-color:#<%= @game.name %>">
  <h1>Welcome to #<%= @game.name %></h1>

  <%= for msg <- @msgs do %>
  <p><%= msg %></p>
  <br/>
  <% end %>

  <form action="#" phx-submit="send-message">
    <input type="text" name="message" placeholder="Message" />
    <input type="submit" value="Send!" />
  </form>
</section>

lib/modern_art_web/templates/game/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div>
    <%= submit "New Game" %>
  </div>
<% end %>

lib/modern_art_web/templates/game/new.html.eex
<h1>New Game</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.game_path(@conn, :create)) %>

lib/modern_art_web/templates/layout/app.html.eex
<main role="main" class="container">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/modern_art_web/templates/layout/live.html.leex
<main role="main" class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/modern_art_web/templates/layout/root.html.leex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "ModernArt", suffix: " · Phoenix Framework" %>
    <link phx-track-static rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer phx-track-static type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul>
            <li><a href="https://hexdocs.pm/phoenix/overview.html">Get Started</a></li>
            <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
              <li><%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home) %></li>
            <% end %>
          </ul>
        </nav>
        <a href="https://phoenixframework.org/" class="phx-logo">
          <img src="<%= Routes.static_path(@conn, "/images/phoenix.png") %>" alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <%= @inner_content %>
  </body>
</html>